### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by JBiOS12-4** [sohsatoh/sohsatoh#1]
If I sponsored you for $30, how would I get those 3 free copies of your "paid software". Does this mean jailbreak tweaks? If so, if I did sponsor you for $30, would these be able for me to give out as part of a giveaway?

**Comment by sohsatoh** [comment]
@JBiOS12-4 Hi!

You are correct in your understanding.
As a reminder, my tweak is uploaded to Packix, so you will need the Packix account of the winner to use the giveaway feature. (Packix does not yet support issuing gift codes).

Also, if you do a giveaway, it would be great if you could let me know the form and your account, just in case.

**Comment by JBiOS12-4** [comment]
I appreciate the response! Yeah I mean I'm just a casual jailbreaker, not an actual group or anything that typically does a giveaway. So I'm entirely new to this but I'll do a bit more research.

If you had the time and could speed this up for me, this is essentially what I'm trying to figure out: if I paid $30 and got 3 free tweaks, I can do the giveaway but I would simply require those 3 people's Packix account in order to actually give away each one. As well, if I did $30 with you, would I be able to split this up into 3 so I can hand 1 free tweak out per person, or would I be required to do all 3 to one person?

As far as the giveaway goes, I can definitely get you my account, but there won't really be a form. It'll simply be a "comment on this post (on Reddit) to enter into the draw". Not sure if I'm supposed to do anything extra, I was just feeling charitable is all (give you $30 and then give 3 others one free tweak each).

**Comment by sohsatoh** [comment]
@JBiOS12-4 There seems to be no problem in doing the giveaway, so you are free to do it:)

>would I be able to split this up into 3 so I can hand 1 free tweak out per person, or would I be required to do all 3 to one person?

There is no problem with such a format. If you give me Packix accounts of three people, I can gift one to each of them.

**Comment by JBiOS12-4** [comment]
Awesome! I'll be in touch within the week. I'll give you the $30 now and be in touch with you shortly. Cheers and thanks for everything you do for the jailbreak community!

**Comment by JBiOS12-4** [comment]
Okay sponsored! I will be in touch with you shortly. Is there a better way for me to connect with you for this? I don't think posting the Packix accounts on here in public may be of much benefit... I tried PM'ing you on Reddit, otherwise I can email you?

**Comment by sohsatoh** [comment]
@JBiOS12-4 Thanks:) I will tell you my email address using Github Sponsors.
It will probably be sent from `noreply@github.com`, so if you see that email, let me know here and I'll be happy to help.

**Comment by JBiOS12-4** [comment]
Any chance you got my email about the winners? Sorry, I don't mean to bug you, but they're asking when the ETA is :$

**Comment by sohsatoh** [comment]
Done
